#!/bin/bash

echo "🔥 AI Access Management - Firebase Setup Guide"
echo "=============================================="
echo ""

echo "📋 Bước 1: Tạo Firebase Project"
echo "1. Truy cập https://console.firebase.google.com"
echo "2. Click 'Create a project'"
echo "3. Đặt tên project (ví dụ: ai-access-management)"
echo "4. Disable Google Analytics (không bắt buộc)"
echo "5. Click 'Create project'"
echo ""

echo "📋 Bước 2: Cấu hình Firestore"
echo "1. Trong Firebase Console, click 'Firestore Database'"
echo "2. Click 'Create database'"
echo "3. Chọn 'Start in test mode'"
echo "4. Chọn location gần nhất (asia-southeast1 cho VN)"
echo ""

echo "📋 Bước 3: Tạo Web App"
echo "1. Click icon '</>' để add web app"
echo "2. Đặt nickname (ví dụ: ai-access-web)"
echo "3. Không check Firebase Hosting"
echo "4. Click 'Register app'"
echo "5. Copy thông tin config"
echo ""

echo "📋 Bước 4: Cập nhật Environment Variables"
echo "Sao chép Firebase config vào file .env.local:"
echo ""
echo "NEXT_PUBLIC_FIREBASE_API_KEY=<apiKey>"
echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=<authDomain>"
echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=<projectId>"
echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=<storageBucket>"
echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=<messagingSenderId>"
echo "NEXT_PUBLIC_FIREBASE_APP_ID=<appId>"
echo ""

echo "📋 Bước 5: Tạo Collections"
echo "Trong Firestore, tạo các collections sau:"
echo "- users"
echo "- products" 
echo "- orders"
echo "- userSubscriptions"
echo ""

echo "📋 Bước 6: Cấu hình Security Rules"
echo "Cập nhật Firestore rules để allow read/write trong development:"
echo ""
echo "rules_version = '2';"
echo "service cloud.firestore {"
echo "  match /databases/{database}/documents {"
echo "    match /{document=**} {"
echo "      allow read, write: if true;"
echo "    }"
echo "  }"
echo "}"
echo ""

echo "✅ Setup hoàn tất!"
echo "Restart development server: npm run dev"
echo ""
